# Matrix Multiplication

Matrix multiplication can be conceptualised in many different ways but the main thing to understand is that it is not commutative, although it is associative.

$$AB \neq BA$$

$$A(BC) = (AB)C$$

The reason why it's not communicative is because each cell of a new matrix is equal to the dot product of the rows in the first matrix, multiplied by the columns in another.

Naturally, this means that this operation only works if the number of rows in matrix A is equal to the number of columns in matrix B resulting in a matrix with the same number of columns as matrix A and rows of matrix B.

This can be remembered in a graphical way:

$$(N_A, M_A) \times (N_B, M_B) = (N_A, M_B)$$

In [12]:
import numpy as np

A = np.random.rand(4,2)

B = np.random.rand(2,3)

In [13]:
# Show that AB works but not BA
A.dot(B)  # Note how the resulting matrix is 4x3 as predicted

array([[0.15640972, 0.21190579, 0.18532092],
       [0.1442303 , 0.2393359 , 0.20422122],
       [0.18316058, 0.28311602, 0.24354705],
       [0.10888771, 0.1531419 , 0.13327841]])

In [15]:
try:
    B.dot(A)
except ValueError:
    print("Matrix operation is invalid.")

Matrix operation is invalid.


## Special Matrices: Diagonal Matrices

Something that is worth knowing is that a matrix that is multipled by a diagonal matrix results in a scaling of each row/column.

In [24]:
C = np.ones((3,3))
D = np.matrix("1 0 0; 0 2 0; 0 0 3")

C.dot(D)  # See how we multiply each column by the number on the diagonal

matrix([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]])

In [25]:
D.dot(C)  # If we do it the other way then we multiply each column by that number

matrix([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])

## But what does a matrix mean?

While it is very interesting how to do matrix multiplication, what does it actually mean? 

A matrix represents an operation on a field on space. This operation consists of two components, a rotation and a stretching. This is why linear algebra can be important when it comes to image processing for instance.

$$ \lambda \begin{bmatrix} cos(\theta) & -sin(\theta) \\ sin(\theta) & cos(\theta) \end{bmatrix} = A$$

We can see above that a $2 \times 2$ matrix A can be expressed by some stretching factor lambda and an according rotation

Note the rotation of doesn't do any stretching, for the length is always one due to this identity:

$$1 = \sqrt{cos^2(\theta) + sin^2(\theta)} = cos^2(\theta) + sin^2(\theta)$$