# Properties of Symmetric Matrices

There are two ways to make symmetric matrices via an additive method and a multiplicative method

## Additive creation of  symmetric matrix

One way to create a symmetric matrix is to sum the matrix by its transpose and normalise that matrix.

$$0.5(AA^T) = S$$

Obviously, this will only work for square matrices.

$$0.5 (\begin{bmatrix} a & b \\ c & d \end{bmatrix} + \begin{bmatrix} a & b \\ c & d \end{bmatrix}^T) = 
0.5 \begin{bmatrix} 2a & b+c \\ c+b & 2d \end{bmatrix}$$

In [1]:
# Import numpy
import numpy as np

In [3]:
A = np.random.rand(2,2)

A

array([[0.85118628, 0.67713968],
       [0.27734151, 0.53320889]])

In [5]:
0.5 * (A + A.T)

array([[0.85118628, 0.4772406 ],
       [0.4772406 , 0.53320889]])

## Multipicative creation of symmetric matrix

Another -more common- way to create a symmetric matrix is simply by multiplying a matrix by its transpose.

However, this will mean that the values found will now take a sort of quadratic form:

$$AA^T = \begin{bmatrix} a^2 + c^2 & ab + cd \\ ab + cd & b^2+d^2 \end{bmatrix}$$

In [6]:
A.dot(A.T)

array([[1.18303624, 0.59712619],
       [0.59712619, 0.36123004]])

Here's a question, if we take two symmetric matrices and multiply them together do we get a symmetric matrix?

Only if they are the same matrix. This is due to the way how matrices are multiplies rows by columns, the order matters and so the numbers on the off-diagonal will not be symmetric.

In [8]:
B = np.random.rand(2,2)

In [10]:
(A.dot(A.T)).dot(B.dot(B.T))

array([[1.1219527 , 1.2868193 ],
       [0.60488408, 0.7020046 ]])