# Challenges

Here, we want to perform a couple of challenges when it comes to matrix multiplication.

In [1]:
import numpy as np

## Challenge 1: matrix multiplication by layering

The challenge here is to implement matrix multiplication by using the "layering" mindset

1. Generate two matrices (square)
2. Build up the matrix product layer-wise
3. Implement matrix multiplication directly
4. Compare the two results

In [2]:
def check_matrix_mult(A, B):
    """
    Checks if it is possible to take the product of two matrices
    """
    
    return A.shape[1] == B.shape[0]

In [3]:
def layer_multiplication(A, B):
    """
    Accepts two matrices A, B and returns the product of the two using a layering algorithm.
    
    The easiest way for me to think about this is by breaking two matrices into their component vectors and 
    taking the column wise outer product from one matrix to the other
    
    :returns: AB
    """
    
    if not check_matrix_mult(A, B):
        print("A and B cannot be multiplied")
        return
    
    # Assuming 2x2 vector
    A_1 = A[:, 0]
    A_2 = A[:, 1]
    B_1 = B[0, :]
    B_2 = B[1, :]
    
    C = np.outer(A_1, B_1)
    D = np.outer(A_2, B_2)
    
    return C + D

In [4]:
# Create random matrices
A, B = np.random.rand(2, 2), np.random.rand(2, 2)

In [5]:
# Print the result of the normal multiplication
A.dot(B)

array([[1.16283895, 1.10558616],
       [0.7953019 , 0.70126742]])

In [6]:
# Print result of layer mulitplication
layer_multiplication(A, B)

array([[1.16283895, 1.10558616],
       [0.7953019 , 0.70126742]])

In [7]:
    A_1 = A[:, 0]
    A_2 = A[:, 1]
    B_1 = B[0, :]
    B_2 = B[1, :]

## Challenge 2: Symmetry of Combined symmetric matrices

1. Create two symmetric matrices
2. Computer sum, multiplication and hadamard multiplication of the two matrices
3. Determine if results are still symmetric

In [8]:
# Create symmetric matrices
E = np.random.rand(2,2)
F = np.random.rand(2,2)

E = E.dot(E.T)
F = F.dot(F.T)

In [9]:
# Sum of symmetric matrices
E + F

array([[1.90849689, 0.6907515 ],
       [0.6907515 , 0.47692845]])

In [10]:
# Multiplication of symmetric matrices
E.dot(F)

array([[1.02395652, 0.46144505],
       [0.37376782, 0.16865873]])

In [11]:
# Haddamard multiplication of symmetric matrices
E*F

array([[0.90967141, 0.11428512],
       [0.11428512, 0.05437361]])

We can we above that only element-wise multiplications will result in a symmetric matrices because the symmetry will be preserved.

Matrix multiplication won't result in a symmetric matrix because of the row-column wise dot products which are non commutative.

## Challenge 3: Standard and Hadamard Mult. for diagonal matrices

1. Create two matrices, one filled with numbers and the other is a diagonal matrix
2. Multiply them by themselves for both standard and haddamard mult.

In [12]:
# Create full matrix
G = np.random.rand(2,2)

# Create diagonal matrix
H = np.random.rand(2,2) * np.identity(2)

In [13]:
# Multiply by themselves standardly
GGt = G.dot(G.T)
HHt = H.dot(H.T)

print(GGt,"\n", HHt)

[[0.0116974  0.02625728]
 [0.02625728 0.96323805]] 
 [[0.44519123 0.        ]
 [0.         0.00204653]]


In [14]:
# Multiply themselves using haddamard
GG = G * G
HH = H * H

print(GG,"\n", HH)

[[1.58970775e-04 1.15384270e-02]
 [9.46269973e-01 1.69680785e-02]] 
 [[0.44519123 0.        ]
 [0.         0.00204653]]


We can see that for the diagonal matrix, hadamard multiplication is the same as normal matrix multiplication.

We can see a proof for this below:

$$\begin{bmatrix} a & 0 \\ 0 & d \end{bmatrix}
\begin{bmatrix} a & 0 \\ 0 & d \end{bmatrix} = \begin{bmatrix} a^2 & 0 \\ 0 & d^2 \end{bmatrix}$$

We can immediately see that this is the same as taking the element wise multiplication.