# Matrix Basics

Now that we have discussed vectors and understood them, we need to understand how to use Matrices.

Matrices are "sheets" of ordered numbers with N rows and M columns. A vector is basically just a matrix with M=1.

If we have a matrix `A`, then we can address a cell by the ith row and the jth column as $a_{ij}$.

$$A=
  \begin{bmatrix}
    a_{11} & a_{12} \\
    a_{21} & a_{21}
  \end{bmatrix}$$
  
Note, that this pattern of rows before columns continues.

In [1]:
# Import numpy 
import numpy as np

In [2]:
# Create matrix A using numpy
A = np.matrix("1 2; 3 4")

A

matrix([[1, 2],
        [3, 4]])

In [4]:
# Selecting the 0th element gives us the first row - a_1i
A[0]

matrix([[1, 2]])

In [5]:
# Select the 0th column
A[:, 0]

matrix([[1],
        [3]])