# Matrix Operations

*Note: Matrix-Matrix Multiplication will get its own section and is not covered in this section.*


## Matrix Addition

Two matrices can be added together as long as they have the same shape (M x N). Pay attention to the fact that I did not use the words "dimension", which can have multiple different meanings.

$$A + B =
  \begin{bmatrix} a_{11} & a_{12} \\ a_{21} & a_{21} \end{bmatrix} + 
  \begin{bmatrix} b_{11} & b_{12} \\ b_{21} & b_{21} \end{bmatrix} = 
  \begin{bmatrix} a_{11}+b_{11} & a_{12}+b_{12} \\ a_{21}+b_{21} & a_{21}+b_{21} \end{bmatrix}
  $$
  
  Note that matrix addition is commutative and associative;
  
  $$(A+B)+C = (B+A)+C = B+(A+C)$$

In [1]:
# Import numpy
import numpy as np

In [2]:
# Create 3 random matrices
A, B, C = np.random.rand(2,2), np.random.rand(2,2), np.random.rand(2,2)

In [3]:
# Show communicative property
assert (A+B).all() == (B+A).all() 

In [4]:
# Show  associative properts
assert ((B+A)+C).all() == (B+(A+C)).all() 

In [5]:
# Addition of two matrices with different shapes
D = np.random.rand(2,3)
C = np.random.rand(3,2)

try: 
    C + D
except:
    print("C and D have different shapes and cannot be added")

C and D have different shapes and cannot be added


The properties above come from the fact that order of addition doesn't matter.

Note. Subtraction follows the same rules as addition.

## Matrix Scalar Multiplication

Matrices can also be multiplied by scalars, because it's the same as adding 

In [6]:
# Multiply 1-matrix by scalar
2 * np.ones((2,2))

array([[2., 2.],
       [2., 2.]])

In [7]:
# We can see that it's the same as adding two one matrices
np.ones((2,2)) + np.ones((2,2))

array([[2., 2.],
       [2., 2.]])

Ofcourse, matrix scalar multiplation also follow the same rules as outlined above for associativity and communicativity.

## Diagonal and Trace

One important component of a matrix are the values that lie on the diagonal. 

There are special functions in numpy that allow you to retrieve the diagonal of a matrix. (Note, a matrix must not be square in order to have a diagonal. They lie on the points $a_{ij}$ where $i = j$.

In [13]:
# Diagonal of a 4x4 matrix
A_4 = np.random.rand(4,4)

A_4.diagonal()

array([0.85641343, 0.80080737, 0.00374232, 0.08367803])

In [10]:
# Doesn't need to be square
np.random.rand(4,5).diagonal()

array([0.90687198, 0.18390978, 0.22647717, 0.55689771])

The `trace` of a matrix is simply the sum of the vector created by $diag(M)$.

In [18]:
# Finding the trace
A_4.trace() == A_4.diagonal().sum()

True