# Matrix Rank

This will be a short section on matrix rank.

The rank of a matrix denotes the amount of informatin found within that matrix. It is usualy indicated by `r` and is a scalar that is always greater than zero.

## How to compute rank

1. Count the number of linearly independent columns
2. Count number of pivots of `row reduced echelon form`
3. Count non-singular values of the SVD
4. Count non-zero eigenvalues for the eigendecomposition

## Rank of added & multiplied matrices

### Addition

$$ rank(A + B) \leq rank(A) + rank(B)$$

We can see above that the rank of two matrices summed together cannot be higher than the rank of both matrices added together.

This is because adding is a linear pooling of information, and that the rank cannot be higher than the higher of the shape of these matrices. (Since they must be the same in order to be summed together.)

In [1]:
import numpy as np

A = np.random.rand(3,3)

A, np.linalg.matrix_rank(A)

(array([[0.89340112, 0.22827182, 0.80535778],
        [0.96982488, 0.6228878 , 0.51562099],
        [0.66159452, 0.45312645, 0.08179519]]), 3)

In [2]:
B = np.random.rand(3,3)

B, np.linalg.matrix_rank(B)

(array([[0.13482742, 0.56880913, 0.6680569 ],
        [0.10774578, 0.08389578, 0.69870325],
        [0.76973461, 0.86245895, 0.52175897]]), 3)

We can calculate rank easily using numpy

In [3]:
np.linalg.matrix_rank(A + B)

3

We can see here that adding two matrices of rank 3 results in another matrix of rank 3

### Multiplication

$$rank(AB) \leq min(rank(A), rank(B))$$

In [4]:
C_rnk1 = np.matrix("1 0 0; 1 0 0; 1 0 0")

C_rnk1, np.linalg.matrix_rank(C_rnk1)

(matrix([[1, 0, 0],
         [1, 0, 0],
         [1, 0, 0]]), 1)

In [5]:
np.linalg.matrix_rank(A.dot(C_rnk1))

1

We can also see that if we multiply two matrices together, then the rank cannot be higher than the lower rank of the two matrices.

## Rank of $A^TA$ and $AA^T$

$$rank(A) = rank(A^TA) = rank(AA^T) = rank(A^T)$$

This rule holds because the rank if not a property of either the column or the row spaces of a matrix but of the matrix itself. Note that this also means that if the dimensionality of the column space is less than the number of columns in a matrix, then the row space will also reflect that since have linearly dependent columns affects the rank.

It's also worth noting that $A^TA$ and $AA^T$ will be full rank matrices, though if A is a rectangular matrix then their shapes will be of different sizes.

In [6]:
np.linalg.matrix_rank(A)

3

In [7]:
np.linalg.matrix_rank(A.T)

3

In [8]:
np.linalg.matrix_rank(A.dot(A.T))

3

In [9]:
np.linalg.matrix_rank(A.T.dot(A))

3

# Shifting in order to get full rank

In order to take a matrix of a lower rank and to make it full rank again, we can add a small amount of information to it.

$$\hat{A} = A + \lambda I$$

Where I is the identity matrix and $\lambda$ is a scaling factor. If we make the scaling factor very small then we can add very little information to obtain full rank. But we need to be careful of noise within the data, if we make this information too small then it will be indistinguisable from that.

Note that depending on noise, it can also be difficult to determine a matrix's rank in the case that its eivenvalues are relatively small and things like that.

In [10]:
lambd = 0.001

C_rnk1 + lambd * np.identity(3), np.linalg.matrix_rank(C_rnk1 + lambd * np.identity(3))

(matrix([[1.001e+00, 0.000e+00, 0.000e+00],
         [1.000e+00, 1.000e-03, 0.000e+00],
         [1.000e+00, 0.000e+00, 1.000e-03]]), 3)