# Challenges

Now that we've learned a little bit about matrix rank, it's time to do some challenges.

In [1]:
import numpy as np

## Challenge :  Reduced-Rank Matrix via Multiplication

1. Create a 10x10 matrix with rank 4

Create two random matrices, and multiply them together such that we get a 10x10 matrix with a rank of 4.

1. First, we need to remember that $rank(AB) \leq min(rank(A), rank(B))$
2. If we multiply two matrices to get 10x10, they need to have dimensions 10xN, and Nx10. (Note that N must be the same number or the multiplication will fail.)
3. What if we generate a matrix 10x4 and then multiply it by its transpose?


In [2]:
# Generate random 10x4 matrix
A = np.random.rand(10, 4) 

A, np.linalg.matrix_rank(A)

(array([[0.13775302, 0.89464813, 0.02958883, 0.28444156],
        [0.04753019, 0.53709216, 0.33140344, 0.1595394 ],
        [0.352461  , 0.23887765, 0.16698934, 0.82475297],
        [0.71993272, 0.23094229, 0.56685519, 0.96515178],
        [0.75901299, 0.77913509, 0.25867247, 0.59057479],
        [0.79993657, 0.48489627, 0.18120488, 0.47439249],
        [0.24680696, 0.48711854, 0.45844026, 0.41432023],
        [0.53269397, 0.60174124, 0.35962109, 0.33139611],
        [0.02549727, 0.07402649, 0.28407881, 0.05200419],
        [0.17570274, 0.12721375, 0.73609531, 0.65431968]]), 4)

Note that it doesnt matter if our matrix is full rank because $AA^T$ will always be full rank

In [3]:
B = A.dot(A.T)

B.shape

(10, 10)

In [4]:
np.linalg.matrix_rank(B)

4

In [5]:
B

array([[0.90115368, 0.54224141, 0.50179906, 0.59708686, 0.97724592,
        0.6843038 , 0.6012127 , 0.71663048, 0.0929377 , 0.34591104],
       [0.54224141, 0.42600817, 0.33197329, 0.50009333, 0.63448828,
        0.43419134, 0.49138741, 0.52055995, 0.14341235, 0.42501098],
       [0.50179906, 0.33197329, 0.88939419, 1.19958573, 0.9839143 ,
        0.81929323, 0.62161804, 0.6648692 , 0.11699881, 0.75488905],
       [0.59708686, 0.50009333, 1.19958573, 1.82448024, 1.44299767,
        1.24846125, 0.94993183, 1.04617195, 0.24667565, 1.20465044],
       [0.97724592, 0.63448828, 0.9839143 , 1.44299767, 1.59884223,
        1.3119989 , 0.93013379, 1.16189762, 0.18122512, 0.80930965],
       [0.6843038 , 0.43419134, 0.81929323, 1.24846125, 1.3119989 ,
        1.13290635, 0.71325389, 0.94028039, 0.13243823, 0.64602493],
       [0.6012127 , 0.49138741, 0.62161804, 0.94993183, 0.93013379,
        0.71325389, 0.68002687, 0.72676079, 0.19413213, 0.71388644],
       [0.71663048, 0.52055995, 0.6648692

Success!

Now that we have done this, we can write a function that will generate any random square matrix with rank N and dimentions MxM.

In [6]:
def generate_fullrank_matrix(rank, dim):
    """
    Generates dim x dim matrix with specified rank.
    
    :returns: full rank square matrix
    """
    
    A = np.random.rand(dim, rank)
    B = A.dot(A.T)
    
    return B
    

In [7]:
generate_fullrank_matrix(4, 10)

array([[1.37866038, 0.63462142, 1.55467827, 1.04059418, 0.46745882,
        1.18810625, 1.01584753, 1.11029588, 0.90414139, 1.13925127],
       [0.63462142, 1.7538341 , 1.32410692, 1.79836697, 1.13454139,
        1.05430669, 1.19723675, 1.25750071, 1.29099682, 1.21942526],
       [1.55467827, 1.32410692, 2.08923938, 1.79968127, 1.01450098,
        1.62036955, 1.53409048, 1.58046205, 1.26846024, 1.47126088],
       [1.04059418, 1.79836697, 1.79968127, 2.13091222, 1.20031657,
        1.45644466, 1.64815988, 1.67250655, 1.38712986, 1.30901106],
       [0.46745882, 1.13454139, 1.01450098, 1.20031657, 0.94567565,
        0.77395471, 0.77226437, 0.72964955, 0.68960889, 0.77291902],
       [1.18810625, 1.05430669, 1.62036955, 1.45644466, 0.77395471,
        1.27478014, 1.26425807, 1.29540242, 0.99627249, 1.09994996],
       [1.01584753, 1.19723675, 1.53409048, 1.64815988, 0.77226437,
        1.26425807, 1.44934595, 1.45915705, 1.02349638, 0.93773937],
       [1.11029588, 1.25750071, 1.5804620

## Challenge 2: Scalar Multiplication and Rank

Is the matrix rank dependant on scalar multiplication?

My hypothesis is, no. This is because multiplying all vectors in a matrix will change nothing about whether that matrix has linearly dependent vectors. 

1. Create a random matrix
2. Reduce the rank by making one column equal to another
3. Multiply it by a scalar
4. Check if the rank changes

In [8]:
# Create reduced rank matrix
C = generate_fullrank_matrix(3, 3)
C[:, 1] = C[:, 2]

C.shape, np.linalg.matrix_rank(C)

((3, 3), 2)

In [9]:
# Multiply C by scalar
D = np.random.rand(1,1) * C

np.linalg.matrix_rank(D)

2

We can see here that it did not effect the rank of the matrix.

## Challenge 3: Rank of Multiplied and Summed Matrices

1. Create two matrices A and B, make them rectangular
2. Create symmetric matrices from A and B
3. Multiply them together in the fasion $(A^TA)(B^TB)$ and compute rank
4. Compute tha rank of $A^TA + B^TB$

In [10]:
E = np.random.rand(2, 5)
F = np.random.rand(2, 5)

E, F

(array([[0.99187859, 0.15989086, 0.9473292 , 0.1287026 , 0.4899314 ],
        [0.92597561, 0.15643875, 0.7487517 , 0.50370112, 0.84861966]]),
 array([[0.67555295, 0.82747311, 0.33309284, 0.49103094, 0.36080436],
        [0.72587747, 0.15185194, 0.4881816 , 0.02552566, 0.94489421]]))

In [11]:
Es = E.T.dot(E)
Fs = F.T.dot(F)

np.linalg.matrix_rank(Es), np.linalg.matrix_rank(Fs)

(2, 2)

In [12]:
Es.shape

(5, 5)

In [13]:
Es

array([[1.84125397, 0.30345079, 1.63296137, 0.59407231, 1.27175357],
       [0.30345079, 0.05003817, 0.26860306, 0.09937674, 0.21109255],
       [1.63296137, 0.26860306, 1.45806173, 0.4990708 , 1.09953174],
       [0.59407231, 0.09937674, 0.4990708 , 0.27027918, 0.49050612],
       [1.27175357, 0.21109255, 1.09953174, 0.49050612, 0.9601881 ]])

In [14]:
# Compare Rank

In [15]:
np.linalg.matrix_rank(Es.dot(Fs)), np.linalg.matrix_rank(Es + Fs)

(2, 4)

We can see that the rank of these matrices are not the same and it has to do with the rules that were outlined during the lectures.

This shows the linear pooling of information, adding two 5x5 matrices with rank 2 that were generated is highly likely to add information to this matrix such that the rank increases from 2 to 4.

If we were to reverse the shape of the matrices E and F and do this operation then the ranks will result as 2 and 2. The reason for this is that we cant pool information beyond what the matrix can hold. (I.e. Es + Fs will be a 2x2 matrix and so the rank cannot be higher than 2.)

## Challenge 4: Is this vector in the span of the set?

Deter mine if this vector is in the span of these sets:

$$v = \begin{bmatrix} 1 \\ 2 \\ 3 \\ 4 \end{bmatrix}$$

$$S = \{\begin{bmatrix} 4 \\ 3 \\ 6 \\ 2 \end{bmatrix}, \begin{bmatrix} 0 \\ 4 \\ 0 \\ 1 \end{bmatrix}\}, 
T = \{\begin{bmatrix} 1 \\ 2 \\ 2 \\ 2 \end{bmatrix}, \begin{bmatrix} 0 \\ 0 \\ 1 \\ 2 \end{bmatrix}\}$$

In [16]:
# Create vector v
v = np.array([1, 2, 3, 4])

# Create sets S and T
S = [np.array([4, 3, 6, 2]), np.array([0, 4, 0, 1])]
T = [np.array([1, 2, 2, 2]), np.array([0, 0, 1, 2])]

Turn S and T into augmented matrices using v to augment matrices made from sets S and T

We can then check the rank of the matrix, if the rank is 3 then v is linearly dependent. (Given the rank of the unaugmented matrix is 2.)

In [17]:
# Concatenate vectors together into a matrix
S.append(v)
S = np.array(S).T

T.append(v)
T = np.array(T).T

print(S)

[[4 0 1]
 [3 4 2]
 [6 0 3]
 [2 1 4]]


In [18]:
np.linalg.matrix_rank(S), np.linalg.matrix_rank(T)

(3, 2)

This is pretty cool! Seems that in the set S, the vector v is linearly independent causing the rank of the matrix to increase whereas for the set T it seems to be linearly dependentant. 