# Matrix Spaces

## Row and Column Vectors

Matrices have contained within them spaces. We've already had some intuition with things such as the column-space, formed by the linearly independent column vectors created from a matrix. 

However, we can also do the same thing with a transposed version of the same matrix A, this is is the row space. (i.e. Row vectors become column vectors after transposition.)

In [4]:
import numpy as np
import scipy.linalg as la

In [3]:
A = np.matrix("1 2 3; 4 5 6; 7 8 9")

A

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

See the matrix above, which is a rank 2 matrix. We can find the basis of the column space of A by using `scipy.linalg`'s `orth` function. 

In [5]:
la.orth(A)

array([[-0.21483724,  0.88723069],
       [-0.52058739,  0.24964395],
       [-0.82633754, -0.38794278]])

Note that we can also find the basis for the row space of this matrix as well

In [7]:
la.orth(A.T)

array([[-0.47967118,  0.77669099],
       [-0.57236779,  0.07568647],
       [-0.66506441, -0.62531805]])

Since we have a 3x3 matrix of rank 2, this matrix also has 2 basis vectors that create a plane in $R^3$. 

## Nullspaces

When performing a linear tranformation using a matrix, remember that the transformation consists of rotations and stretching?

If there are linearly dependant vectors in the column space of a matrix, then the points transformed by that matrix will be "squished" into a lower dimension of space. If we think of a grid of points in $R^2$ then if there is 1 linearly dependent column, these points will be pressed onto a line.

The points that get pressed onto the origin is the left-nullspace. In our example above, the left-nullspace will be a line that is perpendicular to the column space.

In [8]:
A

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

If we remember this matrix from before, we can see that one of the columns is linearly independent meaning that 3d space gets pressed onto a plane. What is the basis for the nullspace of this matrix?

In [20]:
la.null_space(A.T)

array([[ 0.40824829],
       [-0.81649658],
       [ 0.40824829]])

We can see here that we can use numpy to find the basis for the left-nullspace of A. This line will be perpendicular to the plane created by the columns space of A.

In [34]:
# Note that the numbers here are so small that they are practically 0. (i.e. rounding error)
la.orth(A).T.dot(la.null_space(A.T))  

array([[1.11022302e-16],
       [4.99600361e-16]])

## Dimensions of matrix spaces

My favorite way to think of matrix spaces has been outlined by Gilbert Strang in his course posted on MIT OCW.

![](matrix-spaces.png)

We can see here what was found experimentally above, that the number of bases in the column space and the left-null space must equal the number of columns in matrix A. These bases will be in $R^n$ (because each column will have n rows.)

The opposite is also true for the row space and the null space of a matrix. Where the num