# Challenges

## Challenge 1: Determinents of small and large singular matrices

1. Generate a 2x2 matrix with integers that have linear dependence
2. Generate random NxN matrices with linear dependance and compute determinant

In [1]:
import numpy as np
from scipy import linalg as la
import sympy

In [2]:
A_2 = np.random.randint(100, size = (2, 2))

A_2

array([[47, 45],
       [89, 25]])

In [3]:
A_2[:, 1] = A_2[:, 0]

A_2

array([[47, 47],
       [89, 89]])

In [4]:
np.linalg.det(A_2)

-3.3595348725157227e-13

We can already see a small error in calculating the determinant here!

In [5]:
A_30 = np.random.randint(100, size = (30, 30))
A_30[:, 1] = A_30[:, 0]
A_30

array([[32, 32, 55, 47, 80, 57,  8, 51,  8, 77, 71, 99, 48, 68, 48,  9,
        60, 24, 20, 29, 11, 92, 40, 94, 97, 15, 67, 39, 94, 43],
       [70, 70, 95, 65, 99, 44, 26,  1, 64, 91, 88, 64, 51, 22, 46, 62,
        37, 70, 19, 33, 25, 25,  1, 39, 70, 84, 55,  4, 35, 10],
       [45, 45, 82, 68, 10, 20, 54, 91, 82, 42, 56, 53, 53, 51, 81, 67,
        77, 61, 55, 52, 91, 91, 80, 93, 24, 74, 49, 27, 98, 45],
       [12, 12, 18, 44, 52, 94, 89, 46, 39, 34, 38, 28, 46, 63, 19, 36,
        15, 41, 12, 37, 27, 72, 30, 57, 41, 56,  1, 85, 49, 38],
       [ 9,  9,  4, 44, 23, 58, 29, 33,  5, 57, 68, 84,  5, 88, 54, 70,
        13, 39, 81, 49, 28, 19, 33,  1,  0, 47, 66, 76, 35, 12],
       [74, 74, 21, 55, 20, 10,  1, 64, 65, 77, 68, 63, 36, 29, 57, 81,
        86, 33, 80, 99, 86, 19, 92, 83, 77, 39, 57, 39, 47, 35],
       [ 7,  7, 75, 51, 15,  8, 39, 10, 24, 66, 43, 67, 97, 17, 83, 38,
        63,  4, 52, 89, 80, 42, 30, 48, 70, 49, 57, 75, 49,  0],
       [72, 72, 19, 70, 37,  6, 63, 76, 1

In [6]:
np.linalg.det(A_30)

-1.7953390721775357e+45

Yeesh. Not only is the determinant not even small for this 30x30 singular matrix, but the number generated is unrealistically large. This shows the pitfalls of using computers to calculate matrices. But there's absolutely no way you'd calculate this by hand either!