# Orthogonal Matrices

Using the last notebook as a base, we can start thinking of orthogonal matrices.

We can take these two vectors and create an orthogonal matrix (denoted by Q):

In [1]:
import numpy as np

# Create orthogonal matrix
Q = 1/3*np.matrix("2 1; -2 2; 1 2")

Q

matrix([[ 0.66666667,  0.33333333],
        [-0.66666667,  0.66666667],
        [ 0.33333333,  0.66666667]])

Since the basis of the column space of $Q$ are orthogonal, the dot products between the columns and the rows of $Q^T$ will either be 1 or 0, either parallel to itself or orthogonal to itself.

Thus, if we calculate $Q^TQ$ then we will always get I

In [2]:
Q.T.dot(Q)

matrix([[1.00000000e+00, 1.54197642e-17],
        [1.54197642e-17, 1.00000000e+00]])

Note that, once again, the computer has a difficult time expressing 0 and so it shows very small numbers on the off.diagonal

The fact that $Q^TQ = I$ is very useful when doing proofs and other such matrix algebra. 

## Graham Scmidt

The difficulty now is creating an orthogonal matrix from any matrix. Once again, we turn to the column space to find our set of vectors that we will orthogonalise.

We turn the 1st vector into a unit vector and turn c2 into a unit vector perpendicular to c1 and so on until all vectors are othogonal.

Note that by doing this, we lose information about the matrix, since the original can't be reconstructed from the orthogonalised matrix alone.

This algorithm is a little tedious and instead is done though QR decomposition.

## QR Decomposition

When thinking of QR recompostion we want to decompose matrix A into its orthogonal matrix (Q) and the rest of the information stored inside of R. Thus;

$$A = QR$$

It's clear enough how to get Q through Graham Schmidt, but how do we find R? 

$$A = QR$$
$$Q^TA = Q^TQR$$
$$Q^TA = R$$

Note that it is very easy to compute the transpose, so it's pretty easy to compute R

In [3]:
A = np.matrix("1 2 3; 2 2 3; 4 5 6")

A

matrix([[1, 2, 3],
        [2, 2, 3],
        [4, 5, 6]])

In [4]:
Q, R = np.linalg.qr(A)

Q, R

(matrix([[-0.21821789,  0.8468098 , -0.48507125],
         [-0.43643578, -0.52925612, -0.72760688],
         [-0.87287156,  0.05292561,  0.48507125]]),
 matrix([[-4.58257569, -5.67366515, -7.20119038],
         [ 0.        ,  0.89973541,  1.2702147 ],
         [ 0.        ,  0.        , -0.72760688]]))

In [5]:
# Using the dot product here is actually less accurate!
(Q.T).dot(A)

matrix([[-4.58257569e+00, -5.67366515e+00, -7.20119038e+00],
        [-1.22124533e-15,  8.99735411e-01,  1.27021470e+00],
        [ 2.22044605e-16,  5.55111512e-17, -7.27606875e-01]])