# Challenges

## Challenge 01: Inverse via QR

Try and compute inverse using QR decomposition.

1. Create 100x100 random matrix
2. Compute explicit inverse
3. Do QR decomposition
4. Compute inverse via QR
5. Have a look

Note:

$$A = QR$$
$$A^{-1} = (QR)^{-1}$$
$$A^{-1} = R^{-1}Q^T$$

In [1]:
import numpy as np

A = np.random.randint(0, 100, size=(100, 100))

A

array([[39, 60, 86, ..., 58, 76, 85],
       [41, 92, 37, ..., 62, 55, 41],
       [ 9,  0, 54, ..., 33, 15, 90],
       ...,
       [74, 28, 19, ..., 97, 11,  7],
       [76, 40, 33, ..., 85, 37, 73],
       [79,  0, 80, ..., 30, 51, 38]])

In [2]:
# Calculate explicit inverse
np.linalg.inv(A)

array([[ 3.47497904e-03, -6.42008959e-03, -4.70859625e-04, ...,
        -4.13186968e-06,  9.12296631e-03,  7.06248064e-04],
       [ 2.00258434e-03,  2.60802610e-03,  2.38527195e-04, ...,
         1.42034499e-03, -1.59272230e-04, -1.79848817e-03],
       [-1.05626968e-03, -1.11349686e-02,  4.37947139e-03, ...,
        -6.23995206e-03,  4.60480647e-03, -2.86133519e-03],
       ...,
       [-9.30023549e-03,  1.88445278e-04,  1.97582627e-04, ...,
        -4.29776161e-03, -1.19630110e-02, -6.62895810e-03],
       [-7.67367030e-05,  3.05391879e-03, -1.97466105e-03, ...,
         2.19403615e-03, -3.11339634e-03, -1.57682202e-03],
       [ 6.29182417e-03, -1.04748275e-02,  2.42763730e-03, ...,
        -4.78517915e-04,  1.09931437e-02,  2.08622503e-03]])

In [3]:
# Do QR decomp
Q, R = np.linalg.qr(A)

Q, R

(array([[-0.06903628, -0.08181158, -0.12495091, ..., -0.11777873,
          0.12159468, -0.0988168 ],
        [-0.0725766 , -0.16384013,  0.07971492, ..., -0.11955727,
         -0.03988453,  0.16451333],
        [-0.01593145,  0.01838092, -0.15694019, ...,  0.00844501,
         -0.0611327 , -0.03812747],
        ...,
        [-0.13099192,  0.07578299,  0.09053137, ..., -0.0698927 ,
          0.112308  ,  0.00751541],
        [-0.13453224,  0.04757519,  0.06707996, ..., -0.16020512,
          0.04694857, -0.17265379],
        [-0.13984272,  0.16134366, -0.13573231, ..., -0.1564929 ,
         -0.0458619 , -0.03276539]]),
 array([[-564.92034837, -428.73831807, -465.08326485, ..., -473.92875964,
         -439.45487309, -399.04740669],
        [   0.        , -371.60389479, -174.17466333, ..., -160.85832669,
         -184.00199191, -112.92423631],
        [   0.        ,    0.        , -317.26762112, ...,  -80.68021619,
         -138.08029864, -119.80166237],
        ...,
        [   0.    

In [4]:
# Calculate inverse via QR decomposition
np.linalg.inv(R).dot(Q.T)

array([[ 3.47497904e-03, -6.42008959e-03, -4.70859625e-04, ...,
        -4.13186968e-06,  9.12296631e-03,  7.06248064e-04],
       [ 2.00258434e-03,  2.60802610e-03,  2.38527195e-04, ...,
         1.42034499e-03, -1.59272230e-04, -1.79848817e-03],
       [-1.05626968e-03, -1.11349686e-02,  4.37947139e-03, ...,
        -6.23995206e-03,  4.60480647e-03, -2.86133519e-03],
       ...,
       [-9.30023549e-03,  1.88445278e-04,  1.97582627e-04, ...,
        -4.29776161e-03, -1.19630110e-02, -6.62895810e-03],
       [-7.67367030e-05,  3.05391879e-03, -1.97466105e-03, ...,
         2.19403615e-03, -3.11339634e-03, -1.57682202e-03],
       [ 6.29182417e-03, -1.04748275e-02,  2.42763730e-03, ...,
        -4.78517915e-04,  1.09931437e-02,  2.08622503e-03]])

We can see that the two are the same. 