# Matrix Inverses

When given equations like the ones below, we need to solve for x.

$$3x = 1$$

We can find x by multiplying it and the RHS of the equation by the inverse of 3, $3^{-1}$.

$$3^{-1}\times3x = x = 3^{-1}\times1 = \frac{1}{3}$$

If we consider this on the number line, 3 stretches the number line that x is on. My multiplying it by the inverse of 3, we undo that stretching.

The same logic applies when calculating the inverse of a matrix. We want to undo the rotation and stretching operations that it performs.

In [1]:
import numpy as np

In [2]:
A = np.matrix("1 2 3; 4 5 6; 6 6 7")

np.linalg.matrix_rank(A)

3

In [3]:
b = np.array([1, 2, 3])

b

array([1, 2, 3])

Given the equation above, can we solve the following?:

$$\begin{bmatrix}1 & 2 & 3 \\ 4 & 5 & 6 \\ 6 & 6 & 7\end{bmatrix}X = \begin{bmatrix}1\\2\\3\end{bmatrix}$$

We can if we multiply both by the ivnerse of the matrix on the LHS.

In [4]:
# The matrix has an inverse attribute that calls its inverse
A.I.dot(b)

matrix([[ 0.66666667, -1.33333333,  1.        ]])

In [5]:
# We can also use numpy's "solve" function
np.linalg.solve(A, b)

array([ 0.66666667, -1.33333333,  1.        ])

## Inverse of a singular matrix

If a matrix does not have rull rank then the column space will not span the whole abient space. This means that it will be an object with 0 area. If an object has 0 area then it is impossible to know what operation will undo that.

The same is true for scalars, there is no inverse of 0 and so that operation canot be undone.

However, there are a number of operations that can be done to find some inverses anyway.

### Left and Right inverses.

As we already know, if we multiply a matrix by its transpose in any order we will get a full rank square matrix. We can then take the inverse of that matrix to find the left or right inverse.

If we have a tall matrix that has more rows than columns then we can find the full matrix by the following

$$(A^TA)^{-1}A^T$$

If we have a wide matrix, with more columns than rows, then the operations change as follows

$$A^T(AA^T)^{-1}$$

Note that the shapes of the wide and tall matrices differ, so there is no plausible right inverse for a tall matrix and vice versa.

In [6]:
# Create tall matrix
B = A[:, :2]

B

matrix([[1, 2],
        [4, 5],
        [6, 6]])

In [7]:
# Calculate left inverse
(B.T.dot(B)).I.dot(B.T)

matrix([[-0.62962963, -0.37037037,  0.51851852],
        [ 0.59259259,  0.40740741, -0.37037037]])

In [8]:
# Calculate right inverse of B.T
C = B.T
C_i = (C.T.dot(C)).I.dot(C.T)

In [9]:
C.dot(C_i)

matrix([[ 1.   , -1.   ],
        [ 0.125, -0.125]])

In [10]:
C_i.dot(C)

matrix([[-0.125 , -0.125 ,  0.    ],
        [ 1.    ,  1.    ,  0.    ],
        [-0.8125, -0.8125,  0.    ]])

The interesting thing about the left and right invereses is that multiplying these by their original matrices does not result in an identity like matrix.

In any case, these matrices are important when we start thinking about OLS and other more advances linear algebra topics.

### Pseudo Inverse

Matrices also have a pseudo inverse which does recreate the identity matrix as closely as possible. How to calculate it is outside of the scope of this course but I want to note it here anyway.

In [11]:
# Calculate pseudo inverse
C_pinv = np.linalg.pinv(C)

C_pinv

matrix([[-0.62962963,  0.59259259],
        [-0.37037037,  0.40740741],
        [ 0.51851852, -0.37037037]])

In [12]:
C_pinv.dot(C)

matrix([[ 0.55555556,  0.44444444, -0.22222222],
        [ 0.44444444,  0.55555556,  0.22222222],
        [-0.22222222,  0.22222222,  0.88888889]])

## MCA Algorithm to calculate matrix inverse

1. Compute minors
2. Compute cofactors
3. Perform haramard multiplication between the last two matrices and transpose the result
4. Divide each element by the determinent

Only issue, we need to caluclate determinants and we have already seen how this can be difficult using computers. Therefore it is often times not ideal to use matrix inverses in order to solve equations.