# Challenges

## 01: Inverse of Diagonal Matrices

1. Create a diagonal matrix
2. Compute its inverse
3. Extract the diagonals of the matrix and its inverse
4. Multiply them elementwise

In [1]:
import numpy as np

In [2]:
A = np.matrix("3 0; 0 5")

A

matrix([[3, 0],
        [0, 5]])

In [3]:
A.I

matrix([[0.33333333, 0.        ],
        [0.        , 0.2       ]])

In [4]:
np.diag(A), np.diag(A.I)

(array([3, 5]), array([0.33333333, 0.2       ]))

In [5]:
np.diag(A) * np.diag(A.I)

array([1., 1.])

We can see above that multiplying the elment wise diagonal of A and its inverse creates 1s. This is because the basis vectors will simply stretch the matrix in certain directions instead of applying a rotation and so calculating the inverse is relatively easy.

## 02: Pseudoinverse of Invertible Matrices

Is the pseudo inverse of a invertible matrix the same as the full inverse?

In [6]:
A = np.matrix("1 2 3; 4 5 5; 6 7 8")

A.I

matrix([[-1. , -1. ,  1. ],
        [ 0.4,  2. , -1.4],
        [ 0.4, -1. ,  0.6]])

In [7]:
np.linalg.pinv(A)

matrix([[-1. , -1. ,  1. ],
        [ 0.4,  2. , -1.4],
        [ 0.4, -1. ,  0.6]])

We can see here that the pseudo inverse and the full inverse are exactly the same of the matrix is full rank.

This is because the calculating for the pinv is an optimisation getting as close as possible to the actual inverse, which means that if it is possible to calculate the actual inverse then it'll return that.