# Section 1: Vectors

In [2]:
import numpy as np
import matplotlib.pyplot as plt

plt.style.use("seaborn")

A vector can have multiple interpretations. Either as a list of numbers or as a line in some space with length and direction.

Note how the order matters as shown below.

In [11]:
a = np.array([2, 1])

b = np.array([1, 2])

try:
    assert np.array_equal(a, b)
except AssertionError:
    print("Vectors a and b are not equal.")

Vectors a and b are not equal.


Here, I don't do a lot of graphing because I already understand these kinds of basics and it's not very easy to plot vectors in matplotlib.

## Vector Addition

Note that you can add or subtract vectors as long as they occupy the same dimensionality.

In [25]:
a+b

array([3, 3])

In [26]:
a-b

array([ 1, -1])

## Vector-Scalar Multiplication

You can also multiply vectors with scalars (single numbers) by multiplying each component of a vector by the scalar.

In [27]:
2*a

array([4, 2])

Note that this idea can be used to create vector spaces later, where the space created by a vector is equal to the points that can be reached by multiplying by all scalar values.

## Dot Product

The dot product is a very important concept in linear algebra and is best described as multiplying each dimension of a vector and summing all of the results.

$$\sum_{i=1}^{N}x_{i}y_{i}$$

In [31]:
# Dot product using for loops
dot_prod = 0
for i in range(len(a)):
    dot_prod += a[i]*b[i]
    
dot_prod

4

In [29]:
# Dot product using numpy
a.dot(b)

4

## Vector Length

Using the pythagorean theorem, we can also find the length of any vector

$$c^2 = a^2 + b^2$$

Though, an interesting thing to note is that the length of a vector is equal to the square root of the dot product with itself!

In [33]:
# Calculate length brute force
length_a = 0
for i in range(len(a)):
    length_a += a[i]**2

np.sqrt(length_a)

2.23606797749979

In [35]:
# Elegantly through numpy
np.sqrt(a.dot(a))

2.23606797749979

In [36]:
# Using linalg
np.linalg.norm(a)

2.23606797749979

## Dot Product Geometry

Now that we've taken the time to think about the dot product and vector lengths, we should think about what the dot product actually means.

The dot product calculates a value which is a function of the angles between two vectors.

$$\alpha = |a||b|cos(\theta_{a,b})$$

We can derive this by thinking of the law of cosines (pythagorean theorem for all triangles)

$$|a - b|^2 = |a-b|^T|a-b|$$
$$... = a^Ta + b^Tb - 2a^Tb$$

Note that this is possible because $a^Tb = b^Ta$.

Thus, if the law of cosines is $|a-b|^2 = |a|^2 + |b|^2 - 2|a||b|cos(\theta_{a,b})$...

... Then the same law as above pops out!

$$\alpha = |a||b|cos(\theta_{a,b})$$

Given this, can we find the angles between our two vectors, a and b?

In [59]:
# Angle using numpy
np.arccos(a.dot(b) / (np.linalg.norm(a)*np.linalg.norm(b))) * 57.2958  # Note that this calculation returns radians

36.86991082919828

In [54]:
np.(0)

1.5707963267948966

In [57]:
# These are orthogonal
c, d = np.array([1,0]), np.array([0,1])

np.arccos(c.dot(d) / (np.linalg.norm(c)*np.linalg.norm(d))) * 57.2958

90.00003218077504

In [58]:
# We can tell their orthogonal because of their dot product
c.dot(d)

0