# Unit Vectors

A unit vector is a speical type of vector that has a magnitude of 1. 


Useful because they are necessary to understanding basis vectors in a later section.

In [1]:
# Import numpy
import numpy as np

In [2]:
# Create a random vector
v = np.random.randint(0, 100, 2)

v

array([79, 84])

Now that we have created a random vector, let's check that if it is a unit vector:

In [3]:
def unit_vec_chec(v):
    """
    Checks if vector v is a unit vector.
    
    If not a unit vector, returns actual unit vector.
    
    If the vector is the zero-vector, returns NaN.
    
    :return: unit_v
    """
    
    v_len = np.linalg.norm(v)
    
    if v_len == 1:
        print("Vector is a unit vector")
        return v
    elif v_len == 0:
        print("Vector is the zero vector")
        return np.NaN
    else:
        print("Vector is not a unit vector")
        return v/v_len
    
    

In [4]:
# Check if our random vector is a unit vector
unit_vec_chec(v)

Vector is not a unit vector


array([0.68509415, 0.72845454])

In [5]:
# Check if the null vector is a unit vector
unit_vec_chec(np.array([0, 0, 0]))

Vector is the zero vector


nan

In [6]:
# Check if unit vector is a unit vector
unit_vec_chec(np.array([1, 0]))

Vector is a unit vector


array([1, 0])

## Unit vector challenge

Investigate dot products with unit vectors

1. Create two random integer vectors with the same dimension
2. Compute their magnitudes
3. Compute magnituded of the dot-product
4. Normalize the vectors
5. Compute Magnitude of the dot product

In [7]:
# We already have our random integer vector v, so we'll just create another one
w= np.random.randint(0, 100, 2)

v, w

(array([79, 84]), array([28, 20]))

In [8]:
# Compute their magnitudes
np.linalg.norm(v), np.linalg.norm(w)

(115.31261856362468, 34.40930106817051)

In [9]:
# Compute their dot product
v.dot(w)

3892

In [13]:
v_unit = unit_vec_chec(v)
w_unit = unit_vec_chec(w)

v_unit, w_unit

Vector is not a unit vector
Vector is not a unit vector


(array([0.68509415, 0.72845454]), array([0.81373347, 0.58123819]))

In [14]:
v_unit.dot(w_unit)

0.9808896364219445

We can see that the magnitude of the dot product has decreased dramatically. This is because of what the dot product represents:

$$\alpha = |v||w|cos(\theta)$$

This, with unit vectors $|v|$ and $|w|$ are equal to one and so the dot product is just the cosine of the angle between the two vectors.