# Unit Vectors

A unit vector is a speical type of vector that has a magnitude of 1. 


Useful because they are necessary to understanding basis vectors in a later section.

In [1]:
# Import numpy
import numpy as np

In [2]:
# Create a random vector
v = np.random.randint(0, 100, 2)

v

array([15, 98])

Now that we have created a random vector, let's check that if it is a unit vector:

In [7]:
def unit_vec_chec(v):
    """
    Checks if vector v is a unit vector.
    
    If not a unit vector, returns actual unit vector.
    
    If the vector is the zero-vector, returns NaN.
    
    :return: unit_v
    """
    
    v_len = np.linalg.norm(v)
    
    if v_len == 1:
        print("Vector is a unit vector")
        return v
    elif v_len == 0:
        print("Vector is the zero vector")
        return np.NaN
    else:
        print("Vector is not a unit vector")
        return v/v_len
    
    

In [8]:
# Check if our random vector is a unit vector
unit_vec_chec(v)

Vector is not a unit vector


array([ 0.15129919,  0.98848802])

In [9]:
# Check if the null vector is a unit vector
unit_vec_chec(np.array([0, 0, 0]))

Vector is the zero vector


nan

In [10]:
# Check if unit vector is a unit vector
unit_vec_chec(np.array([1, 0]))

Vector is a unit vector


array([1, 0])