# Eigenvectors and Eigenvalues

Before we start talking about eigendecomposition, we need to think about whateigenvectors and eigenvalues are.

Recall that a matrix A can be expressed as some rotating and stretching of a field in some dimension of space. 

Eigenvectors are vectors in this space that do not change their direction after applying the transformation A, but they may be scales by some value (eigenvalue).

$$ Av = \lambda v$$

If we think of this in terms of data, the eivenvectors are the points that have the most variance, this concept is pretty important in statistics.

## How to find Eigenvals and Eigenvecs

### Eigenvalues

If the above equation is true, then so must the following equations:

$$Av - \lambda v = 0$$
$$(A - \lambda I) v = 0$$

Note that when we shift A in this way then it becomes a singular matrix with a determinant of 0.

$$| A - \lambda I | = 0$$

The determinant of this matrix will be an $n^{th}$power polynomial with n solutions, where n is the shape of the square matrix A. (Eigendecomposition does not work for rectangular matrices.)

I won't focus on how exactly we'll do this because this is something I have a computer to do. See notes for more information.



In [20]:
import numpy as np
import sympy as sp

from scipy import linalg as la

A = np.matrix("3 1;4 6")

A

matrix([[3, 1],
        [4, 6]])

In [10]:
# The polynomial for 2x2 matrices is y^2 - tr(A)y + det
trace = int(A.trace())
det = int(np.linalg.det(A))

trace, det

(9, 14)

In [15]:
l = sp.Symbol('x')

l_1, l_2 = sp.solvers.solve(l**2 - trace*l + det, l)

l_1, l_2

(2, 7)

We can see above that the eigenvalues are 2 and 7

### Eigenvectors

Once we have the eigenvalues from the matrix, we can think about how we get the eigenvectors.

We simply substitute lambda for the eigenvalues we attained and find a vector that lies in the nullspace of this matrix. These vectors are the eigenvectors.

In [17]:
# Create eigenvalue matrix (variance matrix)
L = np.zeros(shape=(2, 2))
L[0, 0] = l_1
L[1, 1] = l_2

L

array([[2., 0.],
       [0., 7.]])

In [23]:
# Shift A by l
A_shift = A - np.identity(2)*l_1

# Find basis for nullspace
la.null_space(np.matrix("1 1;4 4"))

array([[ 0.70710678],
       [-0.70710678]])

We can see here that this is a [1, -1] vector that has been scaled to unit length.

In [26]:
# Shift A by l
A_shift = A - np.identity(2)*l_2

# Find basis for nullspace
la.null_space(np.matrix("-4 1; 4 -1"))

array([[0.24253563],
       [0.9701425 ]])

As well, we have found the other eigenvector for this matrix.

## Eigendecomposition

Notice that we can combine our eigenvectors to make an eigenvector matrix V and an eigenvalue matrix D with eigenvalues on the diagonal.

Thus we can turn our previous equation into a matrix equation:

$$ AV = V \Lambda$$

or

$$A = V \Lambda V^{-1}$$

In [31]:
D, L = np.linalg.eig(A)

Dm = np.zeros(shape=(2, 2))
Dm[0, 0] = D[0]
Dm[1, 1] = D[1]

In [32]:
L.dot(Dm).dot(np.linalg.inv(L))

matrix([[3., 1.],
        [4., 6.]])

We can see how we can combine these matrices to create the full matrix again.

One nice property of the eigendecomposition is that it becomes very easy to calculate repeated applications  of the same matrix

$A^TA = V \Lambda V^{-1} V \lambda V^{-1}$

Thus, repeated iterations give you the following...

$A^n = V \Lambda ^n V^{-1}$

Note that this decomposition is valid for singular matrices as well, it's just that some eigenvalues will be 0. (Which makes sense since it denotes an eigenvector being squashed to 0.)

### Eigendecomposition of Symmetric Matrices

It's worth noting that if A is a symmetric matrix then then V will be orthogonal. This is an important point for SVD.